<?xml version='1.0' encoding='UTF-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <repositories>
        <repository>
            <id>mvnflight</id>
            <name>mvnflight SNAPSHOT test repository</name>
            <url>https://jeanbisutti.github.io/mvnflight/repo/SNAPSHOT/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
             </snapshots>
        </repository>
    </repositories>

    <name>Keycloak</name>
    <description>
        Keycloak SSO
    </description>
    <groupId>org.keycloak</groupId>
    <artifactId>keycloak-parent</artifactId>
    <version>999.0.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>io.github.mvnflight</groupId>
            <artifactId>mvnflight-extension</artifactId>
            <version>0.1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
